### ISSUE TITLE
No instance Console log in Horizon

### ISSUE THREAD

**Issue by sudhakarau1** [stackinabox/stackinabox.io#2]
Launching the Ubuntu 14.04 image does not show the console log in Horizon. Might be a case of https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/4/html/Installation_and_Configuration_Guide/Dashboard_Log_Tab_Shows_no_Output_for_Instance.html

**Comment by tpouyer** [comment]
fixed in latest release 0.9.7
