### ISSUE TITLE
Impossible to run - Vagrant 1.8.6 introduces bug

### ISSUE THREAD

**Issue by niklaushirt** [stackinabox/stackinabox.io#3]
Vagrant 1.8.6 introduced a bug:
https://github.com/mitchellh/vagrant/issues/7883

Still works with 1.8.5:
https://releases.hashicorp.com/vagrant/1.8.5/

Should be fixed in 1.8.7.

**Comment by tpouyer** [comment]
I was actually helping somebody out last week who was having some weird issues getting vagrant up to work correctly on windows and found this bug.  In the next release I will tighten down the vagrant version compatibility value to skip the 1.8.6 version.
