### ISSUE TITLE
What is the root/pw for the ubuntu host?

### ISSUE THREAD

**Issue by jcalcada** [stackinabox/stackinabox.io#5]

**Comment by tpouyer** [comment]
you can login as the vagrant user with:

```
username: vagrant
password: vagrant
```

that user has sudo permissions so to execute a process as root you can do this:

```
sudo %command%
```

Replace '%command%' from above with the command you want to run as root.  If you don't want to have to keep typing 'sudo' in front of every command you can run this command to keep root privileges for the duration of your terminal session:

```
sudo -i
```
